# Generated by Django 4.2.6 on 2023-11-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.TextField()),
                ('email', models.CharField(max_length=128)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.classfield')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['student_id'],
            },
        ),
    ]
