# Generated by Django 4.2.6 on 2023-12-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_classfield_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/students/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.specialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.classfield', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.TextField(verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
