# Generated by Django 4.2.6 on 2024-01-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_email_remove_student_login_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='email',
    #     ),
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='login',
    #     ),
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='password',
    #     ),
    # ]
