# Generated by Django 4.2.6 on 2023-12-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_login_remove_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
