# Generated by Django 4.2.6 on 2023-12-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_classfield_options_and_more'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLesson',
            fields=[
                ('plan_lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('numbers_lesson', models.IntegerField(verbose_name='Номер урока')),
                ('start_time', models.DateTimeField(verbose_name='Начало урока')),
                ('end_time', models.DateTimeField(verbose_name='Окончание урока')),
            ],
            options={
                'verbose_name_plural': 'Расписание звонков',
                'ordering': ['plan_lesson_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['mark_id'], 'verbose_name': 'оценка', 'verbose_name_plural': 'оценки'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['schedule_id'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subjects_id'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='specialization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.specialization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(verbose_name='Название предмета'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='plan_lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='diary.planlesson'),
            preserve_default=False,
        ),
    ]
