# Generated by Django 4.2.6 on 2023-12-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_planlesson_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['schedule_id'], 'verbose_name': 'schedule', 'verbose_name_plural': 'schedules'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='plan_lesson',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='specialization',
        ),
        migrations.AddField(
            model_name='schedule',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlanLesson',
        ),
    ]
