# Generated by Django 4.2.6 on 2023-12-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_planlesson_alter_mark_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
