# Generated by Django 4.2.6 on 2024-01-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_classfield_options_and_more'),
        ('diary', '0002_planlesson_alter_mark_options_alter_schedule_options_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='schedule',
        #     name='classroom',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='кабинет'),
        # ),
        # migrations.AddField(
        #     model_name='schedule',
        #     name='semester',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='семестр'),
        # ),
        # migrations.AddField(
        #     model_name='schedule',
        #     name='teacher',
        #     field=models.CharField(blank=True, max_length=250, null=True, verbose_name='преподаватель'),
        # ),
        # migrations.AddField(
        #     model_name='schedule',
        #     name='type_lesson',
        #     field=models.CharField(blank=True, max_length=250, null=True, verbose_name='тип занятия'),
        # ),
        migrations.AlterField(
            model_name='planlesson',
            name='end_time',
            field=models.TimeField(verbose_name='Окончание урока'),
        ),
        migrations.AlterField(
            model_name='planlesson',
            name='start_time',
            field=models.TimeField(verbose_name='Начало урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='class_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.classfield', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_lesson',
            field=models.DateField(verbose_name='дата урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='plan_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.planlesson', verbose_name='номер урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.specialization', verbose_name='специализация'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.subject', verbose_name='предмет'),
        ),
    ]
