# Generated by Django 4.2.6 on 2024-01-17 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_classfield_options_and_more'),
        ('diary', '0003_schedule_classroom_schedule_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.specialization', verbose_name='специализация'),
        ),
    ]
