# Generated by Django 4.2.6 on 2023-12-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_schedule_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlesson',
            name='end_time',
            field=models.TimeField(verbose_name='Окончание урока'),
        ),
        migrations.AlterField(
            model_name='planlesson',
            name='start_time',
            field=models.TimeField(verbose_name='Начало урока'),
        ),
    ]
