# Generated by Django 4.2.6 on 2024-01-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_schedule_specialization'),
    ]

    # operations = [
        # migrations.AddField(
        #     model_name='schedule',
        #     name='classroom',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='кабинет'),
        # ),
        # migrations.AddField(
        #     model_name='schedule',
        #     name='semester',
        #     field=models.IntegerField(blank=True, null=True, verbose_name='семестр'),
        # ),
        # migrations.AddField(
        #     model_name='schedule',
        #     name='teacher',
        #     field=models.CharField(blank=True, max_length=250, null=True, verbose_name='преподаватель'),
        # ),
    #     migrations.AddField(
    #         model_name='schedule',
    #         name='type_lesson',
    #         field=models.CharField(blank=True, max_length=250, null=True, verbose_name='тип занятия'),
    #     ),
    # ]
