# Generated by Django 4.2.6 on 2023-12-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_planlesson_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='type_lesson',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
