# Generated by Django 4.2.6 on 2023-12-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_classfield_options_and_more'),
        ('diary', '0006_schedule_teacher_schedule_type_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='class_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.classfield', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='кабинет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_lesson',
            field=models.DateField(verbose_name='дата урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='plan_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.planlesson', verbose_name='номер урока'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.IntegerField(verbose_name='семестр'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.specialization', verbose_name='специализация'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.subject', verbose_name='предмет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type_lesson',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='тип занятия'),
        ),
    ]
