# Generated by Django 4.2.6 on 2023-11-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.TextField()),
                ('position', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diary.subject')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['teacher_id'],
            },
        ),
    ]
