# Generated by Django 4.2.6 on 2023-12-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/teachers', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.TextField(verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='login',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.TextField(verbose_name='Должность'),
        ),
    ]
