# Generated by Django 4.2.6 on 2023-12-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='login',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
