# Generated by Django 4.2.6 on 2023-12-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
