# Generated by Django 4.2.6 on 2023-12-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_remove_teacher_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='login',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
    ]
