# Generated by Django 4.2.6 on 2023-12-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_remove_teacher_login_remove_teacher_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
