env:
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1

imagePullSecrets:
  - name: gitlab-cr

replicaCount: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  hosts:
    - host: "{{ .Values.CI_FQDN }}"
      paths:
        - "/"
