# Generated by Django 4.2.6 on 2023-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
