# Generated by Django 4.2.6 on 2023-12-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_course_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_id'], 'verbose_name': 'Дополнительный курс', 'verbose_name_plural': 'Дополнительные курсы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['news_id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
