# Generated by Django 4.2.6 on 2023-12-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classfield',
            options={'ordering': ['number'], 'verbose_name': 'Номер курса', 'verbose_name_plural': 'Номера курсов'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.RemoveField(
            model_name='classfield',
            name='semester',
        ),
        migrations.AlterField(
            model_name='classfield',
            name='number',
            field=models.IntegerField(verbose_name='Номер курса'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.TextField(verbose_name='Специализация'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
