# Generated by Django 4.2.6 on 2023-12-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfield',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(),
        ),
    ]
