# Generated by Django 4.2.6 on 2023-12-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfield',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
