# Generated by Django 4.2.6 on 2023-12-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_classfield_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfield',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='groups.specialization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.CharField(max_length=64),
        ),
    ]
